#!/usr/bin/env python

"""
Entry point for WifiStalker tool.
"""

try:
    from wifistalker import main
except ImportError:
    print "Unable to find wifipython module - make sure it's installed"
    print "in your site-packages/dist-packages directories or available at"
    print "PYTHONPATH environment"
    print
    raise

if __name__ == "__main__":
   main.run()
